version: 2

sphinx:
    configuration: doc/conf.py
    builder: html

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - libsnmp40
  jobs:
    post_create_environment:
      - pip install -e . -r doc/requirements.txt --constraint constraints.txt
