version: 2

sphinx:
    configuration: doc/conf.py
    builder: html

python:
    install:
      - requirements: doc/requirements.txt
      - method: pip
        path: .
        extra_requirements:
          - setuptools_scm

build:
  os: ubuntu-22.04
  tools:
    python: "3.7"
