name: Verify linting
on:
  push:
    branches: master
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    name: Lint Python
    steps:
    - uses: actions/checkout@v5
    - uses: astral-sh/ruff-action@v3
      with:
        version: "0.12.0"
